language: android

android:
  components:
    - build-tools-21.1.2
    - build-tools-21.0.2
    - build-tools-23.0.1
    - android-18
    - android-21
    - android-23
    - extra



script:
  - ./gradlew :facebook:test -i
